AddressBook/Controllers/ContactController.cs
using AddressBook.Interfaces;
using AddressBook.Models;
using AddressBook.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AddressBook.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactServices _service;

        private readonly IMapper _mapper;

        public ContactController(IContactServices service , IMapper mapper)
        {
            this._service = service;
            this._mapper = mapper;
        }

        public ActionResult Index()
        {
            var contact = this._service.GetContacts().FirstOrDefault();

            if (contact != null)
            {
                return Redirect("/contact/displaycontactdetails/" + contact.ContactId);
            }

            return View();
        }

        public ActionResult DisplayContactDetails(int id)
        {

            Contact contact = this._service.GetContact(id);

            return View(contact);
        }

        public ActionResult AddContactForm()
        {
            return View("ContactForm");
        }

        public ActionResult EditContactForm(int id) 
        {
            Contact contact = this._service.GetContact(id);
            ContactView contactView = _mapper.Map<ContactView>(contact);
            return View("ContactForm", contactView);
        }

        [HttpPost]
        public ActionResult ContactForm(ContactView contactView)
        {
            ContactView contactViewModel;
            Contact contact = _mapper.Map<Contact>(contactView);
            if (ModelState.IsValid)
            {
                if (contact.ContactId == 0)
                {
                    this._service.AddContact(contact);
                }
                else
                {
                    this._service.EditContact(contact);
                }
                return Redirect("/contact/displaycontactdetails/" + contact.ContactId);
            }
            else
            {
                contactViewModel = _mapper.Map<ContactView>(contact);
                return View(contactView);
            }
        }

        public ActionResult DeleteExistingContact(int id)
        {
            this._service.DeleteContact(id);

            return Redirect("/contact/index");
        }
    }
}

AddressBook/Controllers/ContactListViewComponent.cs
using AddressBook.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AddressBook.Controllers
{
    public class ContactListViewComponent : ViewComponent
    {
        private readonly IContactServices _contactServices;

        public ContactListViewComponent(IContactServices contactServices)
        {
            this._contactServices = contactServices;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            ViewData["ContactsList"] = _contactServices.GetContacts();
            return await Task.FromResult((IViewComponentResult)View("ContactList"));
        }
    }
}

AddressBook/Views/Contact/ContactForm.cshtml
@model AddressBook.ViewModels.ContactView;

@{
    Layout = "~/Views/Shared/AddressBookLayout.cshtml";
    var FormButton = "Add";
}

<div class="model-container" id="model-container">
    <form id='add-contact' class='add-contact' action="/contact/contactform" method="post">
        <a href="/contact/index"><div class="close">&times;</div></a>
        @if(@Model != null && @Model.ContactId!=0)
        {
            FormButton = "Update";
            @Html.TextBoxFor(contact => contact.ContactId,new {type="hidden"})
        }
        else
        {
            FormButton = "Add";
        }
        <div id='contact-name' class='contact-name'>
            <div class='label-mandatory'>
                @Html.LabelFor(contact => contact.ContactName,"Name",new {@class = "label"})
                @Html.ValidationMessageFor(contact => contact.ContactName,"",new {@class = "name-input-mandatory"})
            </div>
            @Html.TextBoxFor(contact => contact.ContactName,"",new {@class = "name-input"})
        </div>
        <div class='contact-email'>
            <div class='label-mandatory'>
                @Html.LabelFor(contact => contact.ContactMail,"Email",new {@class = "label"})
                @Html.ValidationMessageFor(contact => contact.ContactMail,"",new {@class = "email-input-mandatory"})
            </div>
            @Html.TextBoxFor(contact => contact.ContactMail,"",new {@class = "email-input"})
            </div>
        <div class='contact-telephone'>
            <div class='mobile' id='mobile'>
                <div class='label-mandatory'>
                    @Html.LabelFor(contact => contact.ContactMobile,"Mobile",new {@class = "label"})
                    @Html.ValidationMessageFor(contact => contact.ContactMobile,"",new {@class = "mobile-input-mandatory"})
                </div>
                @Html.TextBoxFor(contact => contact.ContactMobile,"",new {@class = "mobile-input"})
            </div>
            <div class='landline' id='landline'>
                @Html.LabelFor(contact => contact.ContactLandline,"Landline",new {@class = "label"})
                @Html.TextBoxFor(contact => contact.ContactLandline,"",new {@class = "landline-input"})
            </div>
        </div>
        <div class='webiste'>
            @Html.LabelFor(contact => contact.ContactWebsite,"Website",new {@class = "label"})
            @Html.TextBoxFor(contact => contact.ContactWebsite,"",new {@class = "website-input"})
        </div>
        <div class='Address'>
            <div class="Address-Dno">
                @Html.LabelFor(contact => contact.ContactDoorNumber,"Door Number",new {@class = "label"})
                @Html.TextBoxFor(contact => contact.ContactDoorNumber,"",new {@class = "address-input"})
            </div>
            <div class="Address-Dno">
                @Html.LabelFor(contact => contact.ContactStreet,"Street",new {@class = "label"})
                @Html.TextBoxFor(contact => contact.ContactStreet,"",new {@class = "address-input"})
            </div>
            <div class="Address-Dno">
                @Html.LabelFor(contact => contact.ContactCity,"City",new {@class = "label"})
                @Html.TextBoxFor(contact => contact.ContactCity,"",new {@class = "address-input"})
            </div>
        </div>
        <input type='submit' value=@FormButton id='add-contact-btn' class='add-contact-btn'/>
    </form>
</div>

AddressBook/Views/Contact/DisplayContactDetails.cshtml
@model AddressBook.Models.Contact;

@{
    Layout = "~/Views/Shared/AddressBookLayout.cshtml";
}

<div class="display-contact">
    <div class='display-contact-header'>
        <div class='contact-name'>
            @Model.ContactName
        </div>
        <div class="changes">
            <a href="/contact/editcontactform/@Model.ContactId">
                <div class='edit' id=@Model.ContactId>
                    <img class="edit-img" src='~/images/edit1.jpg' alt='' width='10px' height='14px'>
                    <input type="button" value="Edit" class="edit-btn" id="edit-btn">
                </div>
            </a>
            <a href="/contact/deleteexistingcontact/@Model.ContactId">
                <div class='delete' id=@Model.ContactId>
                    <img class="delete-img" src='~/images/delete1.png' alt='' width='12px' height='18px'>
                    <input type="button" value="Delete" class="delete-btn" id="delete-btn">
                </div>
            </a> 
        </div>
    </div>
    <div class='display-contact-email'>
        <div class='display-label'>
            Email:
        </div>
        <div class='display-value'>
            &nbsp;@Model.ContactMail
        </div>
    </div>
    <div class='display-contact-telephone'>
        <div class='display-mobile'>
            <div class='display-label'>
                Mobile:
            </div>
            <div class='display-value'>
                &nbsp;@Model.ContactMobile
            </div>
        </div>
        <div class='display-landline'>
            <div class='display-label'>
                Landline:
            </div>
            <div class='display-value'>
                &nbsp;@Model.ContactLandline
            </div>
        </div>
    </div>
    <div class='display-contact-website'>
        <div class='display-label'>
            Website:
        </div>
        <div class='display-value'>
            &nbsp;@Model.ContactWebsite
        </div>
    </div>
    <div class='display-contact-address'>
        <div class='display-label'>
            Address:
        </div>
        <div class='display-value'>
            @Model.ContactAddress
        </div>
    </div>
</div>
<script>
    document.getElementById(@Model.ContactId).style.backgroundColor = "#CEE7F2";
</script>

AddressBook/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AddressBookLayout.cshtml";
}

AddressBook/Views/Shared/AddressBookLayout.cshtml
<html>
<head>
    <link rel='stylesheet' type="text/css" href='~/css/AddressBookLayout.css' asp-append-version="true" />
    <link href='https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;800&family=Open+Sans&family=Roboto&display=swap' rel='stylesheet' />
</head>
<body>
    <div class='header'>
        Address Book
    </div>
    <div class='nav-bar'>
        <ul class='nav-list'>
            <li class="nav-item"><a href="/contact/index">home</a></li>
            <li class="nav-item"><a href="/contact/addcontactform">+ ADD</a></li>
        </ul>
        <div class='blog-icon'>
            <img src='~/images/blog-icon.png' alt='blog-icon'>
        </div>
    </div>
    <div class='page-body'>
        @(await Component.InvokeAsync("ContactList"))
        @RenderBody()
    </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
</html>

AddressBook/Views/Shared/Components/ContactList/ContactList.cshtml
@using AddressBook.Models;
@{
    List<Contact> Contacts = ViewData["ContactsList"] as List<Contact>;
}

<div class="page-contacts" style="display:block">
    <div class='contacts-header'>
        Contacts
    </div>
    <div class='contacts-list' id='contacts-list'>
        @foreach (var contact in Contacts)
        {
            <a href="/Contact/displaycontactdetails/@contact.ContactId">
                <div class="contact-item" id="contact-item">
                    <div class='contact' id="@contact.ContactId">
                        <div class='contact-name'>@contact.ContactName</div>
                        <div class='contact-email'>@contact.ContactMail</div>
                        <div class='contact-mobile'>@contact.ContactMobile</div>
                    </div>
                </div>
            </a>
        }
    </div>
</div>